# Numpy: do Básico ao Avançado

### Criando Numpy Arrays

In [2]:
import numpy as np

#### Array 1D

In [3]:
a = np.array([1, 2, 3, 4 ]) 
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


#### Array 1D de tamanho 10 com valores 0

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Array 5x5 com todos os valores 1

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Array 5x5 com matriz identidade

In [7]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array 7x7 com matriz identidade

In [8]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Array 2D

In [9]:
b = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Array 3D

Cada bloco é essencialmente um array 2D, e eles estão empilhados para formar um array 3D. O formato desse array é (2, 2, 3)

In [10]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Valores aleatórios entre 1 e 15

In [11]:
np.random.randint(1, 15, 3)

array([ 1,  2, 14], dtype=int32)

#### Matriz 3x3 de valores aleatórios

In [12]:
np.random.randint(10, size=(3,3))

array([[3, 6, 1],
       [1, 8, 4],
       [2, 0, 4]], dtype=int32)

#### Bool Datatype

In [13]:
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

#### Matriz de valores de 0 a 15 de 3 em 3

In [14]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

#### Reshape

In [15]:
from numpy import *

a = arange(12)
a = a.reshape(3, 2, 2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


#### Transposição

In [16]:
transposicao = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
transposicao.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [17]:
transposicao.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Transforma para 6x6 e os novos valores serão preenchidos com 0

In [18]:
transposicao.resize((6,6), refcheck=False)
transposicao

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
array = np.array([1, 2, 3, 4, 6, 7, 9])
array.size

7

In [20]:
array2 = np.append(array, [0, 1, 2, 4, 5])
array2

array([1, 2, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

In [21]:
array2.size

12

#### Coloca o número 4 na posição 2

In [22]:
np.insert(array2, 2, 4) 

array([1, 2, 4, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

#### Apaga o elemento de indice 4 da matriz de transposição

In [25]:
np.delete(transposicao, 4) 

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
from numpy import *

a = array([10, 20, 30, 40])
append(a, 50)

array([10, 20, 30, 40, 50])

#### Operações

In [32]:
def media(a):
    return (a[0] + a[-1]) /2

b = array([[1,2,3],
           [4,5,6],
           [7,8,9]])
apply_along_axis(media, 0, b)

array([4., 5., 6.])

In [33]:
a = arange(24).reshape(2,3,4) 
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
a = array([10,20,30])
maxindex = a.argmax()
a[maxindex]

np.int64(30)

In [35]:
a = array([2,0,8,4,1])
a

array([2, 0, 8, 4, 1])

#### Indices do array ordenado usando quicksort

In [36]:
ind = a.argsort()
ind

array([1, 4, 0, 3, 2])

In [37]:
a[ind]

array([0, 1, 2, 4, 8])

#### Array de valores espaçados igualmente dentro de um intervalo, ou seja, gerar valores uniformemente distribuídos dentro de um intervalo

In [38]:
np.linspace(0, 150, 5) # 5 valores dentro desse intervalo

array([  0. ,  37.5,  75. , 112.5, 150. ])

#### Valores aleatórios

In [39]:
np.random.random((4, 3))

array([[0.73229918, 0.56600205, 0.14908473],
       [0.19394915, 0.93441965, 0.37119337],
       [0.33968664, 0.26279445, 0.36786024],
       [0.7819784 , 0.1855964 , 0.31702322]])

#### Atributos

In [40]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a2 =np.arange(12, dtype=float).reshape(3, 4) # matriz
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [42]:
a3 = np.arange(8).reshape(2, 2, 2) # 3D --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a1.shape

(10,)

In [44]:
a2.shape

(3, 4)

In [45]:
a3.shape

(2, 2, 2)

In [46]:
a1.size

10

In [47]:
a2.size

12

In [48]:
a3.size

8

#### Mudando DataType

In [49]:
x = np.array([33, 22, 2.5])
x

array([33. , 22. ,  2.5])

In [50]:
x.astype(int)

array([33, 22,  2])