# Numpy: do Básico ao Avançado

### Criando Numpy Arrays

In [1]:
import numpy as np

#### Array 1D

In [2]:
a = np.array([1, 2, 3, 4 ]) 
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


#### Array 1D de tamanho 10 com valores 0

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Array 5x5 com todos os valores 1

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Array 5x5 com matriz identidade

In [6]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Array 7x7 com matriz identidade

In [7]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Array 2D

In [8]:
b = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Array 3D

Cada bloco é essencialmente um array 2D, e eles estão empilhados para formar um array 3D. O formato desse array é (2, 2, 3)

In [9]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Valores aleatórios entre 1 e 15

In [10]:
np.random.randint(1, 15, 3)

array([ 8, 12,  8], dtype=int32)

#### Matriz 3x3 de valores aleatórios

In [11]:
np.random.randint(10, size=(3,3))

array([[7, 5, 2],
       [9, 2, 6],
       [3, 1, 6]], dtype=int32)

#### Bool Datatype

In [12]:
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

#### Matriz de valores de 0 a 15 de 3 em 3

In [13]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

#### Reshape

In [14]:
from numpy import *

a = arange(12)
a = a.reshape(3, 2, 2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


#### Transposição

In [15]:
transposicao = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
transposicao.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [16]:
transposicao.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### Transforma para 6x6 e os novos valores serão preenchidos com 0

In [17]:
transposicao.resize((6,6), refcheck=False)
transposicao

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [18]:
array = np.array([1, 2, 3, 4, 6, 7, 9])
array.size

7

In [19]:
array2 = np.append(array, [0, 1, 2, 4, 5])
array2

array([1, 2, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

In [20]:
array2.size

12

#### Coloca o número 4 na posição 2

In [21]:
np.insert(array2, 2, 4) 

array([1, 2, 4, 3, 4, 6, 7, 9, 0, 1, 2, 4, 5])

#### Apaga o elemento de indice 4 da matriz de transposição

In [22]:
np.delete(transposicao, 4) 

array([1, 2, 3, 4, 6, 7, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
from numpy import *

a = array([10, 20, 30, 40])
append(a, 50)

array([10, 20, 30, 40, 50])

#### Operações

In [24]:
def media(a):
    return (a[0] + a[-1]) /2

b = array([[1,2,3],
           [4,5,6],
           [7,8,9]])
apply_along_axis(media, 0, b)

array([4., 5., 6.])

In [25]:
a = arange(24).reshape(2,3,4) 
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
a = array([10,20,30])
maxindex = a.argmax()
a[maxindex]

np.int64(30)

In [27]:
a = array([2,0,8,4,1])
a

array([2, 0, 8, 4, 1])

#### Indices do array ordenado usando quicksort

In [28]:
ind = a.argsort()
ind

array([1, 4, 0, 3, 2])

In [29]:
a[ind]

array([0, 1, 2, 4, 8])

#### Array de valores espaçados igualmente dentro de um intervalo, ou seja, gerar valores uniformemente distribuídos dentro de um intervalo

In [30]:
np.linspace(0, 150, 5) # 5 valores dentro desse intervalo

array([  0. ,  37.5,  75. , 112.5, 150. ])

#### Valores aleatórios

In [31]:
np.random.random((4, 3))

array([[0.13407178, 0.28405277, 0.88311566],
       [0.45742494, 0.11317435, 0.52758188],
       [0.02688276, 0.43525075, 0.06441861],
       [0.96745399, 0.29680781, 0.47984727]])

#### Atributos

In [32]:
a1 = np.arange(10) # 1D
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a2 =np.arange(12, dtype=float).reshape(3, 4) # matriz
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [34]:
a3 = np.arange(8).reshape(2, 2, 2) # 3D --> Tensor
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
a1.shape

(10,)

In [36]:
a2.shape

(3, 4)

In [37]:
a3.shape

(2, 2, 2)

In [38]:
a1.size

10

In [39]:
a2.size

12

In [40]:
a3.size

8

#### Mudando DataType

In [41]:
x = np.array([33, 22, 2.5])
x

array([33. , 22. ,  2.5])

In [42]:
x.astype(int)

array([33, 22,  2])

#### Operações

In [43]:
z1 = np.arange(12).reshape(3, 4)
z2 = np.arange(12, 24). reshape(3,4)

In [44]:
z1, z2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

##### Escalares

In [45]:
z1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [46]:
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
z1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [48]:
z1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

##### Relacional

In [49]:
z1 > 2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
z2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

##### Vetorial

In [51]:
z1 + z2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [52]:
z1 / z2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

#### Funções em Array

In [53]:
k = np.random.random((3,3)) # valores aleatórios entre 0 e 1
k = np.round(k*100) # multiplica os valores por 100 e os arredonda para o inteiro mais próximo
k

array([[86., 94., 95.],
       [55., 15.,  5.],
       [56., 90., 96.]])

In [59]:
np.max(k), np.min(k), np.prod(k)

(np.float64(96.0), np.float64(5.0), np.float64(1532765203200000.0))

#### Slicing

In [68]:
p1 = np.arange(10)
p2 = np.arange(12).reshape(3,4)

In [61]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
p1[2:5]

array([2, 3, 4])

In [63]:
p1[2:5:2] # pega um e pula um

array([2, 4])

In [64]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
p2[0, :]

array([0, 1, 2, 3])

In [66]:
p2[1:3 ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [67]:
p2[::2, ::3] # seleciona linhas alternadas e colunas a cada 3

array([[ 0,  3],
       [ 8, 11]])

### Iterações

In [69]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
for i in p1:
    print(p1[i])

0
1
2
3
4
5
6
7
8
9


In [72]:
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [74]:
p3 = np.arange(8).reshape(2,2,2)

for i in np.nditer(p3): # percorre de forma linear como se fosse uma matriz 1D
    print(i)

0
1
2
3
4
5
6
7


### Reshape

Converter qualquer dimensão para 1D com Ravel

In [75]:
p2.shape

(3, 4)

In [78]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
p2.ravel().shape

(12,)

Empilhar arrays numpy com Stacking

In [79]:
w1 = np.arange(12).reshape(3,4)
w2 = np.arange(12,24).reshape(3,4)

w1, w2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [82]:
np.hstack((w1, w2)) # empilhou horizontalmente

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [83]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Dividir array com Split

In [84]:
np.hsplit(w1, 2) # divide em dois horizontalmente

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [85]:
np.vsplit(w2, 3) # divide em tres verticalmente

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]