# Numpy: do Básico ao Avançado

### Criando Numpy Arrays

In [1]:
import numpy as np

Array 1D

In [2]:
a = np.array([1, 2, 3, 4 ]) 
print(a)

[1 2 3 4]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


Array 1D de tamanho 10 com valores 0

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Array 5x5 com todos os valores 1

In [5]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Array 5x5 com matriz identidade

In [8]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Array 7x7 com matriz identidade

In [17]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

Array 2D

In [10]:
b = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Array 3D

Cada bloco é essencialmente um array 2D, e eles estão empilhados para formar um array 3D. O formato desse array é (2, 2, 3)

In [14]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Valores aleatórios entre 1 e 15

In [13]:
np.random.randint(1, 15, 3)

array([4, 4, 1], dtype=int32)

Matriz 3x3 de valores aleatórios

In [15]:
np.random.randint(10, size=(3,3))

array([[7, 6, 3],
       [2, 7, 5],
       [5, 7, 6]], dtype=int32)

Bool Datatype

In [16]:
np.array([1, 2, 3], dtype=bool)

array([ True,  True,  True])

Matriz de valores de 0 a 15 de 3 em 3

In [18]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

Reshape

In [20]:
from numpy import *

a = arange(12)
a = a.reshape(3, 2, 2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


Transposição

In [21]:
transposicao = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
transposicao.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
transposicao.reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Transforma para 6x6 e os novos valores serão preenchidos com 0

In [23]:
transposicao.resize((6,6), refcheck=False)
transposicao

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])